name: Build and Push Node.js Image to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - gitops-deploy


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # adjust if needed

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Image
      env:
        ECR_REPO: ${{ secrets.NODE_APP }}
      run: |
        docker build -t $ECR_REPO:$GITHUB_SHA ./node-app
        docker push $ECR_REPO:$GITHUB_SHA